spring.application.name=ecommerce
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=aB3xR9kLpQz7VtN2mW8yJhU5cF6dE1sG4oI0nT9rP2qX7vZ3mK8jH5wY6eR1uL0
jwt.expiration-seconds=86400
